### ISSUE TITLE
Not Sending Any Responses/Submissions

### ISSUE THREAD

**Issue by OGBlooketCheater** [ADIBzTER/borang-chrome-extension#7]
I tried the extension but it wont work pls fix it @ADIBzTER

**Comment by OGBlooketCheater** [comment]
fix plz i want to nuke my teachers form to rig it

**Comment by OGBlooketCheater** [comment]
the one with most votes has to wear a husky suit

**Comment by ADIBzTER** [comment]
Hey @OGBlooketCheater, how do you know it's not working? The form is owned by your teacher right?

**Comment by OGBlooketCheater** [comment]
> Hey @OGBlooketCheater, how do you know it's not working? The form is owned by your teacher right?

I tested it on my own form after trying on my teachers doc and it didnt send any submits

**Comment by OGBlooketCheater** [comment]
for mine

**Comment by ADIBzTER** [comment]
Mind to record how you use Borang and your Google Form settings?

**Comment by OGBlooketCheater** [comment]
> Mind to record how you use Borang and your Google Form settings?

sure ill show you

**Comment by OGBlooketCheater** [comment]
OMG AS SOON AS I START RECORDING IT WORKS

**Comment by OGBlooketCheater** [comment]
it says the video file is to big to send

**Comment by ADIBzTER** [comment]
Well, if it works. No need to send me the recording. Feel free to close this issue

**Comment by OGBlooketCheater** [comment]
Okay i guess the exstion is a little bit buggy ig

**Comment by OGBlooketCheater** [comment]
ill close this
